#!/bin/ksh

#to run this script: sbatch batch_run_python_script.sh 


#for MJO in 3 4 5 6 7 8 ; do
#
#	#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_with_confidence_intervals.py ${MJO}
#	
#	python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py ${MJO}
#	
#done


#python compute_ECMWF_ensemble_members_track_intensity_statistics_multi-year_with_confidence_intervals.py
#
#python compute_ECMWF_ensemble_members_translation_speed_statistics_multi-year_with_confidence_intervals.py
#
##python extract_tc_related_forecast_precip_ECMWF.py
#
#
#
#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 1 2
#
#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 2 3
#
#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 3 4
#
#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 4 5
#
#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 5 6
#
#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 6 7
#
#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 7 8
#
#python compute_ECMWF_ensemble_members_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 8 1



#python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 1 2
#python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 2 3
#python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 3 4
python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 4 5
python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 5 6
python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 6 7
python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 7 8 
python compute_ECMWF_hres_control_ensmean_track_intensity_statistics_per_MJO_phase_PAIRS_with_confidence_intervals.py 8 1



